sudo: required

dist: xenial

env:
  global:
    - CAN_FAIL=false
    - RELEASE_TAG_DOWNSTREAM=0
    - RELEASE_TAG="$TRAVIS_TAG"
    - BRANCH="$TRAVIS_BRANCH"

services:
  - docker

language: go

cache:
  directories:
    - $HOME/.cache/go-build

go:
  - 1.14.7

addons:
  apt:
    update: true

install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

before_script:
  - make test
  - make verify-src

script:
  - make exporter-image EXPORTER_IMAGE=m-exporter-amd64

after_success:
  - make push EXPORTER_IMAGE=m-exporter-amd64

notifications:
  email:
    recipients:
    - kiran.mova@mayadata.io
    - shubham.bajpai@mayadata.io
